version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
      - cd app # Change directory to app
      - mvn install -DskipTests # Installing dependencies without tests
      - echo "Installing jq..."
      - apt-get update && apt-get install -y jq  # Install jq using apt-get

  build:
    commands:
      - echo "Building project..."
      - mvn -B package # Building the project

artifacts:
  files:
    - target/*.war
  name: build-output
