version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
      - cd app # Change directory to app
      - mvn install -DskipTests

  build:
    commands:
      - echo "Building the project..."
      - mvn -B package # Build the project and generate artifacts

  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "Downloading Veracode Pipeline Scanner..."
      - docker pull veracode/api-wrapper-java
      - echo "Running Veracode Static Analysis..."
      - docker run --rm \
          -e VERACODE_API_ID=$VERACODE_API_ID \
          -e VERACODE_API_KEY=$VERACODE_API_KEY \
          -v $(pwd):/data \
          veracode/api-wrapper-java \
          -action uploadandscan \
          -vid $VERACODE_API_ID \
          -vkey $VERACODE_API_KEY \
          -file /data/app/target/verademo.war
      - echo "Veracode Static Analysis completed successfully!"

artifacts:
  files:
    - app/target/*.war # Include the built artifact
