#Build stuff##
version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
      - cd app # Change directory to app
      - mvn install -DskipTests
  build:
    commands:
      - echo "Building project..."
      - mvn -B package
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - app/target/*.war # Look for the .war file



